### PR TITLE
Output from cas when run on scope.v and cas.x.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Data for "la" to "amper" is from scope, and "ca" to "c6" is from cas.  However, input data for "c6" seems truncated and the output is too.

### CODE REVIEW

**Comment by philbudne** [comment]
This is machine generated output, right?

Any reason it can't be created in the Makefile by running cas under a7out?

**Comment by larsbrinkhoff** [comment]
Yes, it's generated by cas from scope.v and cas.x.

Running it with a7out sounds like a good idea, but I get many errors.

```
Use of uninitialized value $val in right bitshift (>>) at ./tools/a7out line 1395.
...
(****WRITE TO LOW MEMORY 00 ****)^
break at PC 010211

**Comment by philbudne** [comment]
> Use of uninitialized value $val in right bitshift (>>) at ./tools/a7out line 1395.

I didn't see that, but it quit on a bad write request
(trying to write zero words)....  I've made that a noop!

In the doubtful case we can't get it working satisfactorily under
a7out, I think the "other" directory would be a better place for a
generated file.

p

**Comment by larsbrinkhoff** [comment]
Ok.

**Pull request closed without merging**
