### PR TITLE
Fix typo in bc.s after manual review.

### PR DESCRIPTION
**Pull request by sebras**

### CODE REVIEW

**Comment by teverett** [comment]
I've checked this PR against the pdf and it is a good fix.  Here is a screen shot of the pdf.

Can we pull this?

Screen Shot 2020-03-14 at 2 18 14 PM

**Comment by sebras** [comment]
> Can we pull this?

Please do, I don't know of any problems with my proposed commit.

**Comment by teverett** [comment]
@philbudne there are a bunch like this.  Before I pull them, are there any objections?

**Comment by philbudne** [comment]
@teverett go ahead.  I try to look at each pdf before pulling.

My enthusiasm was dampened by the number of "fixes" that seem to be  white space only.

**Comment by teverett** [comment]
@philbudne I'll put the documentation ones first, then check each of the rest and pull them.

**Comment by sebras** [comment]
@teverett Thank you!

**Pull request merged**
