### PR TITLE
Fix typos in p?.s.

### PR DESCRIPTION
**Pull request by sebras**
After this commit `tools/as7 ./scans/p?.s` finished without compilation errors and the source code files match the scans to the best of my knowledge.

### CODE REVIEW

**Comment by teverett** [comment]
What program is this?  I dont see it in the /scans/readme ?

**Comment by sebras** [comment]
> What program is this? I dont see it in the /scans/readme ?

Someone (like me in the beginning) forgot to addit to `scans/README.md`. I'll fix it.

**Comment by philbudne** [comment]
I just took care of updating README.md, and I merged p0.s onto the end of op.s

**Comment by sebras** [comment]
> I just took care of updating README.md, and I merged p0.s onto the end of op.s

I noticed that! :) I adjusted the page range for `p4.s` since a few page numbers were missing. I hope that it's correct now.

**Pull request merged**
