### PR TITLE
Fix typos in multiple files.

### PR DESCRIPTION
**Pull request by sebras**
Relying on the assembler to tease out some typos seems to pay off.

### CODE REVIEW

**Comment by aap** [comment]
This in cas.s  is also wrong `o1770072: 0170072`. correct is `o170072`

**Comment by philbudne** [comment]
NOTE! cas.s also exists in src/cmd/cas.s
any fixes should also be reflected there!

**Comment by sebras** [comment]
> This in cas.s is also wrong `o1770072: 0170072`. correct is `o170072`

So it is. I have not done any ocular inspection on these. I just ran them through the assembler to tease out the typos.

**Comment by larsbrinkhoff** [comment]
I think src/cmd/cas.s has those fixes already.

**Comment by sebras** [comment]
> NOTE! cas.s also exists in src/cmd/cas.s any fixes should also be reflected there!

I wasn't aware that `cas.s` (or other files) was available in multiple instances. Perhaps we can address those in `src/cmd/` in separate commits? At the moment I have been focusing on getting the source to match the scans.

**Comment by philbudne** [comment]
How about cmd/adm.s, cmd/apr.s and cmd/as.s?

I'll confess, I didn't always back-port the fixes I found when debugging to the scan directory!

**Comment by philbudne** [comment]
> Perhaps we can address those in src/cmd/ in separate commits? A

Sure!  In fact if you push additional changes to the branch you used to open the PR, they will become part of the existing PR! (hint hint)

**Comment by teverett** [comment]
So ok to pull this?

**Comment by sebras** [comment]
> So ok to pull this?

Give me a second.

**Comment by sebras** [comment]
> Sure! In fact if you push additional changes to the branch you used to open
> the PR, they will become part of the existing PR! (hint hint)

I know. :) I was just uncertain whether that was desired or not.
I just added a commit updating the files under `src/cmd/*` where I
was able to spot differences to the files under `scans/*`. Please vet
these so I haven't made any mistakes.

**Comment by teverett** [comment]
you've got some changes here that are on my branch too.  I'll pull yours then fix mine :)

**Pull request merged**
