### PR TITLE
readded ln dd ken . link for curdir

### PR DESCRIPTION
**Pull request by decuser**
fix for issue #115

### CODE REVIEW

**Comment by sebras** [comment]
> fix for issue #115

Ah! Thank you! It would have been useful to me if this was part of `README.md`. :)

**Comment by philbudne** [comment]
Is the "." entry to make Warren's "ls" program happy?
It appears the original ls program wants a ".." entry!

**Comment by DoctorWkt** [comment]
Yes, the '.' is for my ls to work. The tools/mkfs7 program has a --dotdot option to add '..' to each directory. Maybe we need to use this when building the file system?

**Comment by philbudne** [comment]
@DoctorWkt: The current theory is that '..' is a link to the CURRENT directory!
I'm trying this:
```
diff --git a/tools/mkfs7 b/tools/mkfs7
index aef67a2..8fb7424 100755
--- a/tools/mkfs7
+++ b/tools/mkfs7
@@ -360,8 +360,11 @@ sub make_dir {
     if (!$no_dd) {
       add_direntry( "dd", $Dirstack[0]->[2] );
       dprintf("Added a dd entry to i-num %d\n", $Dirstack[0]->[2] );
+      if (!$wantdotdot && !$wantdot) { # PLB 2019
+       add_direntry( "..", $inum );
+       dprint("Added a .. entry to ourselves\n");
+      }
     }
```

**Pull request merged**
