### PR TITLE
Fix and include psych in the built system.

### PR DESCRIPTION
**Pull request by sebras**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Perhaps post some screenshots to show what it's doing?

**Comment by sebras** [comment]
> Perhaps post some screenshots to show what it's doing?

Sure thing. The program displays geometric figures like these.
You can interactively change from one to the other and change
the zoom-level (compare the relatively small star):

**Comment by philbudne** [comment]
pretty pictures!

(commit works around as7 that "xx" cannot be redefined as a user symbol)

**Comment by sebras** [comment]
@philbudne Thanks for helping out in making sure this (and moo) got in proper. :)

**Pull request merged**
