### PR TITLE
Fix out of range octal constant to make Space Travel build.

### PR DESCRIPTION
**Pull request by sebras**
An octal constant in Space Travel appears to be out of range.
Changing it makes it compile successfully.

I elected to let constant remain unchanged in the transcribed source code file
so it reflects the scan, while I updated the source code file included in the build.

### CODE REVIEW

**Comment by philbudne** [comment]
How does the native assembler deal with the (invalid) value?  Maybe the Perl assembler need to be adjusted?!

**Comment by philbudne** [comment]
Looking at cmd/as.s, it's as I suspected.  It doesn't look to me like it rejects non-octal characters in an octal constant:

```   sad o60                      " zero?
   jmp 1f                       "  yes
   lac d10                      " no: process as decimal
   jmp 2f
1:
   lac d8                       " leading zero: process as octal
2:
   dac num2                     " save radix

num1:
   lac rand+1                   " get number
   cll                          " clear link
   mul                          " mutiply by radix
num2: 0                         " (radix stored here)
   lacq                         " get multiply result
   tad char                     " add char
   tad dm48                     " subtract '0'
   dac rand+1                   " save
   jms gchar                    " get another
   sad d7                       " digit?
   jmp num1                     "  yes: process
```

**Comment by philbudne** [comment]
Opened an alternative PR to change as7 (perl) behavior to match as.s: https://github.com/DoctorWkt/pdp7-unix/pull/226

**Comment by sebras** [comment]
> How does the native assembler deal with the (invalid) value? Maybe the Perl assembler need to be adjusted?!

That indeed looks to be correct. I had forgotten we have the `as` binary, so I never tested to compile Space Travel using it.

I'll close this PR in preference for getting #226 merged.

**Pull request closed without merging**
