### PR TITLE
WORK IN PROGRESS: build a char table, include in boot track

### PR DESCRIPTION
**Pull request by philbudne**
simplify boot paper tape (do one xfer of 4K, instead of 3K+1K)

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Travis CI complains:

```
Can't locate DateTime.pm in @INC (you may need to install the DateTime module)
(@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ../tools/a7out line 10.

**Comment by teverett** [comment]
@larsbrinkhoff I think this can be fixed with a change to the travis file to install the missing module

https://docs.travis-ci.com/user/languages/perl/

**Comment by larsbrinkhoff** [comment]
Thanks @teverett.  This isn't a "perl project" because .travis.yml says `langauge: c`.  So I don't think the `cpanm` tool is available.

Maybe we can just add `apt-get install libdatetime-perl`.

**Comment by teverett** [comment]
@philbudne good to go now?

**Comment by philbudne** [comment]
@teverett  Most recent travis run failed.

**Comment by teverett** [comment]
@philbudne yes I see that.  I'm not sure why. When I pulled your commit onto a branch with this commit it worked fine.

**Pull request closed without merging**
