### PR TITLE
Makefile changes

### PR DESCRIPTION
**Pull request by teverett**

### CODE REVIEW

**Comment by DoctorWkt** [comment]
Tom, I just made similar changes to the Makefile. Can you see what I did and make changes to the new Makefiles?
Cheers, Warren

**Comment by teverett** [comment]
I looked at your versions, and felt that my changes were more extensive.
Could you consider my changes?

On Sat, Mar 19, 2016 at 5:33 PM, Warren <notifications@github.com> wrote:

> Tom, I just made similar changes to the Makefile. Can you see what I did
> and make changes to the new Makefiles?
> Cheers, Warren
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DoctorWkt/pdp7-unix/pull/53#issuecomment-198806588>
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by DoctorWkt** [comment]
On Sat, Mar 19, 2016 at 04:34:52PM -0700, Tom Everett wrote:
>    I looked at your versions, and felt that my changes were more
>    extensive.
>    Could you consider my changes?

Were they made after my changes? If so, sure. I was just worried that
we'd done them at the same time :)

Cheers, Warren

**Comment by teverett** [comment]
I think I started a couple minutes before you... but checked in later.
 <smile>


On Sat, Mar 19, 2016 at 5:35 PM, Warren <notifications@github.com> wrote:

> On Sat, Mar 19, 2016 at 04:34:52PM -0700, Tom Everett wrote:
> > I looked at your versions, and felt that my changes were more
> > extensive.
> > Could you consider my changes?
>
> Were they made after my changes? If so, sure. I was just worried that
> we'd done them at the same time :)
>
>
> Cheers, Warren
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DoctorWkt/pdp7-unix/pull/53#issuecomment-198807377>
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Pull request closed without merging**
