### PR TITLE
Rename and edit scope.x similar to make it adhere to the format of cas.x

### PR DESCRIPTION
**Pull request by sebras**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Since you are renaming...  I'm guessing scope.x was maybe named that
becuase its contents were uncertain.  Now we know it's a definition for
character shapes, and it's an input for cas.  So in this light, maybe
the .x can be reconsidered.  On the other hand, I don't have any better
suggestions and maybe it's fine as is.

**Comment by sebras** [comment]
> Since you are renaming... I'm guessing scope.x was maybe named that becuase 
> its contents were uncertain. 

I named it `scope.v` from the beginning, mainly because it was not assembler, so
I was unsure what to name it. It was only later that I realized that what was part of
`scans/cas.s` had been separated out into `src/cmd/cas.x`. Upon discovering this
I decided to follow the pattern that was established before `scope.v` was added.
I had no deeper thoughts about how the data were to be used. :)

> Now we know it's a definition for character shapes, and it's an input for cas. 
> So in this light, maybe the .x can be reconsidered.  On the other hand, I don't
> have any better suggestions and maybe it's fine as is.

I can do that if desired, but I'm not quite sure what to rename both `cas.x` and
`scope.x` to in that case. Do we know of any other input data for `cas`? If so,
what are those named?

**Comment by larsbrinkhoff** [comment]
I haven't seen any other input files, and I think it's unlikely to be any.  The two together define all printable ASCII characters.  (Except part of 6 is missing.)

**Comment by larsbrinkhoff** [comment]
I'll rattle off some possibly ill considered suggestions:

- .cas
- .in
- .char
- .g2
- .x

**Comment by sebras** [comment]
> (Except part of 6 is missing.)

I believe I addressed this in another [pull request](https://github.com/DoctorWkt/pdp7-unix/pull/138) which has already been merged, that affected characters 2, 6 and 9.

**Comment by larsbrinkhoff** [comment]
The comment below still applies.  After "ka" we expect more input, ending with three lines "x nm r".  Also, displaying the data shows that the symbol isn't complete.

```
:c6
x	x
ck	ck
v	v
ai	ai
ac	ac
ca	ca
ka	ka
" The end of file seems abrupt, every other :cX section ends with:	" The end of file seems abrupt, every other :cX section ends with:
" x	" x
" mn	" mn
" r	" r

**Comment by sebras** [comment]
> The comment below still applies. After "ka" we expect more input,  ending with 
> three lines "x nm r". Also, displaying the data shows that the symbol isn't complete.

I'm confused by this. The contents you cite is not what I see [in the git at `src/cmd/cas.x`](https://github.com/DoctorWkt/pdp7-unix/blob/master/src/cmd/cas.x#L482) where
the modified/corrected file is located. The file `scans/cas.x` is meant to match
the scanned PDF, and so still contains the reordering error, and missing end of `:c9`.

**Comment by philbudne** [comment]
My vote would be .cas (for now) and to add it to the list of questions to ask people who were there at the time.

**Comment by larsbrinkhoff** [comment]
@sebras, what's your source for the updated src/cmd/cas.x?

My source is https://www.tuhs.org/Archive/Distributions/Research/McIlroy_v0/04-cas.pdf, and I don't see a complete c6 there.

I don't view the order of the numbers as a error.  It's arguably preferable to have them in numerical order, but not very important.  In cases like this I prefer historical accuracy.

**Comment by sebras** [comment]
> @sebras, what's your source for the updated src/cmd/cas.x?
>My source is https://www.tuhs.org/Archive/Distributions/Research/McIlroy_v0/04-cas.pdf, 
> and I don't see a complete c6 there. 

My source is the same! The thing is that I started to look at the labels mentioned on
pages 14, 15, 16 and 17 and saw this order:
* page 14 `:cv`, `:cx`, `:cy`
* page 15 `:cz`, `:c0`, `:c1`, `:c2`
* page 16: `:c7`, `:c8`, `:c9`
* page 17: `:c3`, `:c4`, `:c5`, `:c6`

And then I made a guess that the numbers probably should be in ascending order
just like all letters and digits in `cas.x` and `scope.x`. When I rearranged the pages
like so:

* page 14 `:cv`, `:cx`, `:cy`
* page 15 `:cz`, `:c0`, `:c1`, `:c2`
* page 17: `:c3`, `:c4`, `:c5`, `:c6`
* page 16: `:c7`, `:c8`, `:c9`

...they would be in ascending order. This resolves the issue with `:c6` being
truncated. `:c9` still has the trailing `r` statment truncated, but it already ends
with `x` and `mn`, so it is quite likely that that there is an `r` missing at the end
of page 16.

> I don't view the order of the numbers as a error. It's arguably preferable to have them in numerical 
> order, but not very important. In cases like this I prefer historical accuracy.

I fully agree with you, hence I kept the order in `scans/cas.x` as they are in `04-cas.pdf`.
But I still think the pages in 04-cas.pdf were scanned out of order. As I have understood
it the files in `src/cmd/*` are supposed to be the modified/corrected versions that needed
to understand/run the code. Hence I proposed to reorder the pages and add the trailing
`r` statement to `:c9` there.

**Comment by larsbrinkhoff** [comment]
Oh, excellent!  Then the character set is complete.  Thanks for catching this, and the explanation.

**Comment by sebras** [comment]
> Oh, excellent! Then the character set is complete. Thanks for catching this, and the explanation.

Yes, I believe that it is. Sorry for not explaining it clearer before. :)

**Comment by philbudne** [comment]
I'll confess I think two copies of the files (as opposed to branches)
have always seemed like a pain to me, and Warren should be the final
aribiter of whether to reorder the pages in the scans directory, but
for me the difference between the scan and src directories is that the
"scan" versions have only comment annotations indicated by handwriting
on the printouts, while the src versions have annotations added to
help undertstand the code (often times added while debugging).

I tried to make all my annotations be of the form:
	<one or more tabs>" comment

so they can be stripped (and perhaps this should be done for files
loaded onto the disk image!).  In any file I typed or annotated, I
tried to ONLY use tabs for annotation comments, tho more recently it's
been argued that the original files used tabs, with tab stops on the
TTY37 set at three spaces.

Warren played with modifying the system and tools to behave as he
thought they ought to, and that might have been the genesis of the src
files, but I think in the end I might have convinced him those changes
belonged in a branch.

p

**Comment by DoctorWkt** [comment]
Phil mentioned the scans files. I think they should be an accurate transcription from the original PDFs that reflect the original authors' intentions. They should also be useful to the reader. I'd vote for reordering the content to reflect the proper order of the contents, not to reflect the mis-ordered scan of the contents.

**Comment by sebras** [comment]
@DoctorWkt: 
> Phil mentioned the scans files. I think they should be an accurate transcription from the original PDFs that reflect the original authors' intentions. They should also be useful to the reader. I'd vote for reordering the content to reflect the proper order of the contents, not to reflect the mis-ordered scan of the contents.

In that case I intend to provide a pull request to that effect -- including adding the missing `r` statement at the end of the file. In that pull request I also intend to rename `cas.x` to `cas.cas` and will update **this** pull request to accordingly rename `scope.v` to `scope.cas`. I hope this will make everyone satisfied, if not, let me know how I can improve the submissions.

**Comment by sebras** [comment]
I have updated this pull request, but because both #139 and #144 concern the same file, there will be a conflict. Please merge #139 first as that would make more sense when it comes to the commit messages.

**Pull request merged**
